//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmCAROverdue
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Product
    {
        public Master_Product()
        {
            this.QCReject = new HashSet<QCReject>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public int plant_id { get; set; }
        public Nullable<bool> product_del_flag { get; set; }
        public Nullable<int> group_id { get; set; }
    
        public virtual ICollection<QCReject> QCReject { get; set; }
        public virtual Master_Plant Master_Plant { get; set; }
    }
}
