//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmCAROverdue
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempEmail
    {
        public int qc_reject_id { get; set; }
        public string email { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<byte> type { get; set; }
    }
}
