//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcQIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionLot
    {
        public System.DateTime entry_date { get; set; }
        public int plant_id { get; set; }
        public int product_id { get; set; }
        public Nullable<int> qty { get; set; }
    
        public virtual Main Main { get; set; }
        public virtual Master_Product Master_Product { get; set; }
    }
}
