//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcQIS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QISEntities : DbContext
    {
        public QISEntities()
            : base("name=QISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Car> Car { get; set; }
        public DbSet<InspectionLot> InspectionLot { get; set; }
        public DbSet<Main> Main { get; set; }
        public DbSet<Master_Plant> Master_Plant { get; set; }
        public DbSet<Master_Product> Master_Product { get; set; }
        public DbSet<QCReject> QCReject { get; set; }
        public DbSet<AuthUser> AuthUser { get; set; }
    }
}
