//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcQIS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tnc_user
    {
        public string emp_code { get; set; }
        public string emp_title { get; set; }
        public string emp_fname { get; set; }
        public string emp_lname { get; set; }
        public string emp_sex { get; set; }
        public Nullable<byte> emp_position { get; set; }
        public Nullable<byte> emp_group { get; set; }
        public Nullable<byte> emp_depart { get; set; }
        public Nullable<byte> emp_plant { get; set; }
        public Nullable<System.DateTime> emp_joindate { get; set; }
        public string emp_status { get; set; }
        [Display(Name = "Username")]
        public string username { get; set; }
        [Display(Name = "Password")]
        public string password { get; set; }
        public string email { get; set; }
        public string img_path { get; set; }
        public Nullable<byte> admin_role { get; set; }
        public string createby { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
        public Nullable<int> ext { get; set; }
        public Nullable<byte> emp_subgroup { get; set; }
        public string windows_user { get; set; }
        public string ip { get; set; }
        public string transfer_permission { get; set; }
        public string ad_user { get; set; }
    }
}
