//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QISEmailReminder
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthUser
    {
        public AuthUser()
        {
            this.QCReject = new HashSet<QCReject>();
        }
    
        public string user_code { get; set; }
        public byte utype_id { get; set; }
        public int plant_id { get; set; }
    
        public virtual Master_Plant Master_Plant { get; set; }
        public virtual Master_UType Master_UType { get; set; }
        public virtual ICollection<QCReject> QCReject { get; set; }
    }
}
