//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QISEmailReminder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Status
    {
        public Master_Status()
        {
            this.QCReject = new HashSet<QCReject>();
        }
    
        public int status_id { get; set; }
        public string status_name { get; set; }
    
        public virtual ICollection<QCReject> QCReject { get; set; }
    }
}
