//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QISEmailReminder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_OperateUType
    {
        public Master_OperateUType()
        {
            this.OperateUser = new HashSet<OperateUser>();
        }
    
        public byte outype_id { get; set; }
        public string outype_name { get; set; }
    
        public virtual ICollection<OperateUser> OperateUser { get; set; }
    }
}
