//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QISEmailReminder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public string user_code { get; set; }
        public int msg_id { get; set; }
        public int count { get; set; }
    
        public virtual Master_Message Master_Message { get; set; }
    }
}
