//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QISEmailReminder
{
    using System;
    using System.Collections.Generic;
    
    public partial class QCReject
    {
        public QCReject()
        {
            this.OperateUser = new HashSet<OperateUser>();
            this.Rejected_Log = new HashSet<Rejected_Log>();
        }
    
        public System.DateTime entry_date { get; set; }
        public int plant_id { get; set; }
        public int qc_reject_id { get; set; }
        public int product_id { get; set; }
        public string item_code { get; set; }
        public string lot_no { get; set; }
        public string problem { get; set; }
        public string defective_lv { get; set; }
        public string picture { get; set; }
        public byte issue_car { get; set; }
        public string inspector { get; set; }
        public string screener { get; set; }
        public string shift { get; set; }
        public int status_id { get; set; }
        public System.DateTime issue_dt { get; set; }
        public string user_code { get; set; }
    
        public virtual Approved_Log Approved_Log { get; set; }
        public virtual AuthUser AuthUser { get; set; }
        public virtual Car Car { get; set; }
        public virtual Main Main { get; set; }
        public virtual Master_Product Master_Product { get; set; }
        public virtual Master_Status Master_Status { get; set; }
        public virtual ICollection<OperateUser> OperateUser { get; set; }
        public virtual ICollection<Rejected_Log> Rejected_Log { get; set; }
    }
}
