//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QISEmailReminder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tnc_default_permission
    {
        public string emp_code { get; set; }
        public Nullable<byte> level { get; set; }
        public Nullable<byte> approve { get; set; }
    }
}
