//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QISEmailReminder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tnc_costcentercode
    {
        public int id { get; set; }
        public Nullable<int> plant_id { get; set; }
        public Nullable<int> dept_id { get; set; }
        public Nullable<int> group_id { get; set; }
        public int subgroup_id { get; set; }
        public string cost_code { get; set; }
        public bool active { get; set; }
    }
}
