//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcQIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Division
    {
        public string DivId { get; set; }
        public string DivName { get; set; }
        public string MrgEmpId { get; set; }
        public string FieldId { get; set; }
        public Nullable<System.DateTime> OracleLastUpdate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<bool> AutoUpdate { get; set; }
        public Nullable<bool> IsObsolete { get; set; }
        public Nullable<System.DateTime> ObsoleteDate { get; set; }
    }
}
