//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcQIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string EmpId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FirstNameTh { get; set; }
        public string LastNameTh { get; set; }
        public string PositionId { get; set; }
        public string SubGroupId { get; set; }
        public string GroupId { get; set; }
        public string DeptId { get; set; }
        public string DivId { get; set; }
        public string FieldId { get; set; }
        public string FactoryId { get; set; }
        public string AreaId { get; set; }
        public string Ext { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<short> Nation { get; set; }
        public string Sex { get; set; }
        public Nullable<short> Status { get; set; }
        public string Address { get; set; }
        public string SubDistId { get; set; }
        public string DistrictId { get; set; }
        public string ProvinceId { get; set; }
        public string PostCode { get; set; }
        public string Telephone { get; set; }
        public Nullable<System.DateTime> OracleLastUpdate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<bool> AutoUpdate { get; set; }
        public Nullable<bool> IsObsolete { get; set; }
        public Nullable<System.DateTime> ObsoleteDate { get; set; }
    }
}
