//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcQIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Plant
    {
        public Master_Plant()
        {
            this.AuthUser = new HashSet<AuthUser>();
            this.InspectionLot = new HashSet<InspectionLot>();
            this.Main = new HashSet<Main>();
            this.Master_Product = new HashSet<Master_Product>();
        }
    
        public int plant_id { get; set; }
        public string plant_name { get; set; }
        public Nullable<bool> plant_del_flag { get; set; }
    
        public virtual ICollection<AuthUser> AuthUser { get; set; }
        public virtual ICollection<InspectionLot> InspectionLot { get; set; }
        public virtual ICollection<Main> Main { get; set; }
        public virtual ICollection<Master_Product> Master_Product { get; set; }
    }
}
