//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcQIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_UType
    {
        public Master_UType()
        {
            this.AuthUser = new HashSet<AuthUser>();
        }
    
        public byte utype_id { get; set; }
        public string utype_name { get; set; }
    
        public virtual ICollection<AuthUser> AuthUser { get; set; }
    }
}
