//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcQIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Message
    {
        public Master_Message()
        {
            this.Message = new HashSet<Message>();
        }
    
        public int msg_id { get; set; }
        public string msg_word { get; set; }
        public string msg_type { get; set; }
    
        public virtual ICollection<Message> Message { get; set; }
    }
}
