//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcQIS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QISEntities : DbContext
    {
        public QISEntities()
            : base("name=QISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Approved_Log> Approved_Log { get; set; }
        public DbSet<AuthUser> AuthUser { get; set; }
        public DbSet<Car> Car { get; set; }
        public DbSet<InspectionLot> InspectionLot { get; set; }
        public DbSet<Main> Main { get; set; }
        public DbSet<Master_Message> Master_Message { get; set; }
        public DbSet<Master_OperateUType> Master_OperateUType { get; set; }
        public DbSet<Master_Plant> Master_Plant { get; set; }
        public DbSet<Master_Product> Master_Product { get; set; }
        public DbSet<Master_Status> Master_Status { get; set; }
        public DbSet<Master_UType> Master_UType { get; set; }
        public DbSet<Message> Message { get; set; }
        public DbSet<OperateUser> OperateUser { get; set; }
        public DbSet<QCReject> QCReject { get; set; }
        public DbSet<Rejected_Log> Rejected_Log { get; set; }
        public DbSet<v_SumDate> v_SumDate { get; set; }
        public DbSet<v_SumMonth> v_SumMonth { get; set; }
        public DbSet<v_SumYear> v_SumYear { get; set; }
        public DbSet<TempEmail> TempEmail { get; set; }
    }
}
