//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcQIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperateUser
    {
        public int qc_reject_id { get; set; }
        public string emp_id { get; set; }
        public System.DateTime entry_date { get; set; }
        public byte outype_id { get; set; }
        public int plant_id { get; set; }
    
        public virtual Master_OperateUType Master_OperateUType { get; set; }
        public virtual QCReject QCReject { get; set; }
    }
}
