//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcQIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Organization
    {
        public string cost_code { get; set; }
        public bool active { get; set; }
        public Nullable<int> plant_id { get; set; }
        public string plant_name { get; set; }
        public string PlantMgr { get; set; }
        public string PlantMgr_email { get; set; }
        public Nullable<int> dept_id { get; set; }
        public string dept_name { get; set; }
        public string DeptMgr { get; set; }
        public string DeptMgr_email { get; set; }
        public Nullable<int> group_id { get; set; }
        public string group_name { get; set; }
        public string GroupMgr { get; set; }
        public string GroupMgr_email { get; set; }
        public int subgroup_id { get; set; }
        public string sub_group { get; set; }
        public Nullable<int> IsRealCostCode { get; set; }
        public Nullable<int> LeafId { get; set; }
        public Nullable<int> LeafLevel { get; set; }
        public string LeafTitle { get; set; }
    }
}
